Improve error if cassettes dir does not exist
Previously, the error message would be along the lines of:

    IOError: [Errno 2] No such file or directory: 'vcr/cassettes/test.json'

which isn't too helpful. After this patch, it now raises:

    betamax.exceptions.MissingDirectoryError: Configured cassette directory 'vcr/cassettes' does not exist - try creating it